version: "3"

services:
  server:
    image: gitea/gitea:main-nightly
    container_name: gitea_app
    env_file:
      - .env
    restart: always
    networks:
      - gitea
      - reverseproxy
    volumes:
      - gitea_data:/data
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "3000:3000"
      - "222:22"
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: gitea_db
    restart: always
    env_file:
      - .env
    networks:
      - gitea
    volumes:
      - gitea_db:/var/lib/mysql

networks:
  gitea:
    external: false
  reverseproxy:
    external: true

volumes:
  gitea_db:
    external: true
  gitea_data:
    external: true